name: Linting

on: [push, pull_request]

jobs:
  eslint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: npm install, and lint
        run: |
          npm install
          npm run lint
